"""Add Prompt model and link to Chat

Revision ID: 9d7da324e0ff
Revises: e4975ca8a49c
Create Date: 2025-09-01 15:58:45.030295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7da324e0ff'
down_revision = 'e4975ca8a49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_prompt_id', sa.Integer(), nullable=True))
        # --- ИСПРАВЛЕНИЕ: Мы вручную задаем имя для внешнего ключа ---
        batch_op.create_foreign_key('fk_chat_active_prompt_id_prompt', 'prompt', ['active_prompt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        # --- ИСПРАВЛЕНИЕ: Указываем то же имя при удалении ---
        batch_op.drop_constraint('fk_chat_active_prompt_id_prompt', type_='foreignkey')
        batch_op.drop_column('active_prompt_id')

    op.drop_table('prompt')
    # ### end Alembic commands ###
