"""Add vector_id to Message model

Revision ID: e4975ca8a49c
Revises: ed7a54430308
Create Date: 2025-09-01 15:45:09.480902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4975ca8a49c'
down_revision = 'ed7a54430308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_message_vector_id", ['vector_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint("uq_message_vector_id", type_='unique')
        batch_op.drop_column('vector_id')
    # ### end Alembic commands ###
